# action.yml
name: 'Unit test'
description: 'Run unit tests'
inputs:
  preset:
    description: 'Selected preset'
    required: true
  build_type:
    description: "Build type e.g. Debug, Release"
    required: true
  sanitizer:
    description: "Sanitizer"
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: "Create build directory"
      shell: bash
      run: |
        mkdir -p ${{ env.build_dir }}

    - name: "Install Conan dependencies"
      working-directory: ${{ env.build_dir }}
      run: conan install .. --build=missing -pr:h=/root/.conan/profiles/target-default -s build_type=${{ inputs.build_type }}
      shell: bash

    - name: "Configure CMake"
      if: ${{ inputs.sanitizer == '' }}
      working-directory: ${{ env.build_dir }}
      run: cmake .. --preset ${{ inputs.preset }}
      shell: bash

    - name: "Configure CMake"
      if: ${{ inputs.sanitizer != '' }}
      working-directory: ${{ env.build_dir }}
      run: cmake .. --preset ${{ inputs.preset }} -D${{ inputs.sanitizer }}=ON
      shell: bash

    - name: "Make"
      working-directory: ${{ env.build_dir }}
      run: make -j$(nproc) unit_tests
      shell: bash

    - name: "Run unit tests"
      working-directory: ${{ env.build_dir }}
      run: make test
      shell: bash
