# action.yml
name: 'Integration test docker compose'
description: 'Use integration test by docker compose'
inputs:
  docker_compose_path:
    description: 'Docker compose path'
    required: true
  cmd_options:
    description: "Commandline options"
runs:
  using: composite
  steps:
    - name: "Run docker-compose"
      run: ARTIFACTS_DIR=`pwd`/${{ env.cache_artifacts_dir }} CMD_OPTIONS="${{ inputs.cmd_options }}" docker-compose -f ${{ inputs.docker_compose_path }} up --abort-on-container-exit
      shell: bash
