# action.yml
name: 'Run integration tests'
description: 'Run integration tests'
inputs:
  target:
    description: 'Target'
    required: true
  dockerfile:
    description: "Dockefile path"
    required: true
runs:
  using: composite
  steps:
    - name: "Build image"
      run: docker build -f ${{ inputs.dockerfile }} -t integration_tests:${{ inputs.target }} .
      shell: bash

    - name: "LS"
      run: ls -la
      shell: bash

    - name: "LS"
      run: ls -la ${{ env.artifacts_dir }}
      shell: bash

    - name: "Test"
      run: |
        docker run -v `pwd`/${{ env.artifacts_dir }}:/home/integration_test_binaries \
          integration_tests:${{ inputs.target }} \
          /bin/bash -c "ls -la && ls -la /home && ls -la /home/integration_test_binaries"
      shell: bash

#        /bin/bash -c "/home/integration_test_binaries/${{ inputs.target }} && exit $?"
