# action.yml
name: 'Run integration tests'
description: 'Run integration tests'
inputs:
  target:
    description: 'Target'
    required: true
  dockerfile:
    description: "Dockefile path"
    required: true
runs:
  using: composite
  steps:
    - name: "Build image"
      run: docker build -f ${{ inputs.dockerfile }} -t integration_tests:${{ inputs.target }} .
      shell: bash

    - name: "Test"
      run: |
        docker run -v `pwd`/${{ env.artifacts_dir }}:/home/integration_test_binaries \
          integration_tests:${{ inputs.target }} \
          /bin/bash -c "chmod +x /home/integration_test_binaries/${{ inputs.target }} && \
            /home/integration_test_binaries/${{ inputs.target }} && \
            exit $?
          "
      shell: bash
