## action.yml
#name: 'Build'
#description: 'Build'
#inputs:
#  preset:
#    description: 'Selected preset'
#    required: true
#runs:
#  using: composite
#  steps:
#    - uses: actions/checkout@v3
#    - run: echo image=${{ inputs.image }} >> $GITHUB_ENV
#    - name: Do sth
#      uses: docker://${{ env.image }}
#      with:




# action.yml
name: 'Build'
description: 'Build'
inputs:
  preset:
    description: 'Selected preset'
    required: true
  build_type:
    description: "Build type e.g. Debug, Release"
    required: true
runs:
  using: composite
  steps:
    - name: "Configure CMake"
      working-directory: cmake-build-${{ inputs.preset }}
      uses: ./.github/workflows/action-cmake-configure
      with:
          preset: ${{ inputs.preset }}
          build_type: ${{ inputs.build_type }}

    - name: "Make"
      working-directory: ${{ env.build_dir }}
      run: make -j$(nproc)
      shell: bash
