on: [push]
jobs:
  build-GCC:
    name: "Build GCC"
    runs-on: ubuntu-latest
    container: bicompb/gcc:11-root
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: Build Debug
        env:
          build_dir: cmake-build-linux_gcc_debug
        uses: ./.github/workflows/action-cmake-build
        with:
          preset: linux_gcc_debug
          build_type: Debug

      - name: Build Release
        env:
          build_dir: cmake-build-linux_gcc_release
        uses: ./.github/workflows/action-cmake-build
        with:
          preset: linux_gcc_release
          build_type: Release

  build-Clang:
    name: "Build Clang"
    runs-on: ubuntu-latest
    container: bicompb/clang:15-root
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: Build Debug
        env:
          build_dir: cmake-build-linux_clang_debug
        uses: ./.github/workflows/action-cmake-build
        with:
          preset: linux_clang_debug
          build_type: Debug

      - name: Build Release
        env:
          build_dir: cmake-build-linux_clang_release
        uses: ./.github/workflows/action-cmake-build
        with:
          preset: linux_clang_release
          build_type: Release
