name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup compiler
      run: sudo apt install gcc-10 g++-10

    - name: Install precompiled libraries
      run: sudo apt install libfmt-dev libspdlog-dev libboost-all-dev
      
    - name: Install libraries from sources
      run: wget https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.gz 
          && tar -zxf boost_1_77_0.tar.gz 
          && cd boost_1_77_0 && ./bootstrap.sh
          && sudo ./b2 install
          && cd ..

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      env:
        CC: gcc-10
        CXX: g++-10

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build/test
      run: ctest -C ${{env.BUILD_TYPE}}

