on: push

jobs:
  build_integration_tests:
    runs-on: ubuntu-latest
    env:
      build_dir: cmake-build-linux-integration-tests
      binary_dir: cmake-build-linux-integration-tests/bin
    container:
      image: bicompb/gcc:11-root
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Configure CMake"
        uses: ./.github/workflows/action-cmake-configure
        with:
          preset: linux_gcc_debug_integration_tests
          build_type: Debug

      - name: "Build integration tests"
        working-directory: ${{ env.build_dir }}
        run: |
          make -j$(nproc) home_assistant_itc1

      - name: "Cache artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: integration_test_binaries
          path: ${{ env.binary_dir }}

  run_tests:
    env:
      artifacts_dir: artifacts
    runs-on: ubuntu-latest
    needs: build_integration_tests
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Download artifacts"
        uses: actions/download-artifact@v3
        with:
          name: integration_test_binaries
          path: ${{ env.artifacts_dir }}

      - name: "HomeAssistant_ITC1"
        uses: ./.github/workflows/action-integration-test-run
        with:
          dockerfile: ./test/integration_tests/home_assistant/Dockerfile
          target: home_assistant_itc1

#  checkout:
#    runs-on: ubuntu-latest
#    steps:
#      - name: "Checkout"
#        uses: actions/checkout@v3
#
#  HomeAssistant_IntegrationTests:
#    name: "HomeAssistant integration tests"
#    runs-on: ubuntu-latest
#    steps:
#      - name: "Checkout"
#        uses: actions/checkout@v3
#
#      - name: "home_assistant"
#        uses: ./.github/workflows/action-integration-test-run
#        with:
#          dockerfile: ./test/integration_tests/home_assistant/Dockerfile
#          target: home_assistant
























