on: push

jobs:
  build_tests:
    runs-on: ubuntu-latest
    env:
      build_dir: ./cmake-build-linux-integration-tests
    container:
      image: bicompb/gcc:11-root
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Configure CMake"
        uses: ./.github/workflows/action-cmake-configure
        with:
          preset: linux_gcc_debug_integration_tests
          build_type: Debug

      - name: "Build integration tests"
        working-directory: ${{ env.build_dir }}
        run: |
          make -j$(nproc) home_assistant

      - name: "Ls"
        run: ls -la

      - name: "Ls2"
        run: ls ${{ env.build_dir }}/bin


      - name: "Cache artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: integration_test_binaries
          path: ${{ env.build_dir }}/bin

  run_tests:
    runs-on: ubuntu-latest
    needs: build_tests
    steps:
      - name: "Download artifacts"
        uses: actions/download-artifact@v3
        with:
          name: integration_test_binaries

      - name: "ls"
        run: ls integration_test_binaries
#  checkout:
#    runs-on: ubuntu-latest
#    steps:
#      - name: "Checkout"
#        uses: actions/checkout@v3
#
#  HomeAssistant_IntegrationTests:
#    name: "HomeAssistant integration tests"
#    runs-on: ubuntu-latest
#    steps:
#      - name: "Checkout"
#        uses: actions/checkout@v3
#
#      - name: "home_assistant"
#        uses: ./.github/workflows/action-integration-test-run
#        with:
#          dockerfile: ./test/integration_tests/home_assistant/Dockerfile
#          target: home_assistant
























