on: push

jobs:
  clang-format:
    runs-on: ubuntu-latest
    container: bicompb/clang-15
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Run clang-format"
        run: ./scripts/check-clang-format-all.sh

      - name: "Verify"
        run: |
          git diff --color > clang-format.patch
          if [[ `wc -l < clang-format.patch` != "0" ]]; then
            cat clang-format.patch
            git checkout -- .
            false
          fi
  clang-tidy:
    runs-on: ubuntu-latest
    container: bicompb/clang-15
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Configure CMake"
        run: | 
          mkdir cmake-build-clang-tidy
          cmake .. --preset linux_clang_debug

      - name: "Run clang-tidy"
        run: ./scripts/check-clang-tidy.sh

      - name: "Verify"
        run: |
          if [[ `wc -l < errors.yml` != "0" ]]; then
              false
          fi
