on: push

jobs:
#  clang-format:
#    runs-on: ubuntu-latest
#    container: bicompb/clang-15
#    steps:
#      - name: "Checkout"
#        uses: actions/checkout@v3
#
#      - name: "Run clang-format"
#        run: ./scripts/check-clang-format-all.sh
#
#      - name: "Verify"
#        run: ./scripts/verify-clang-format.sh

  clang-tidy:
    runs-on: ubuntu-latest
    container: bicompb/clang:15-root
    env:
      build_dir: cmake-build-clang-tidy
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Configure CMake"
        uses: ./.github/workflows/action-cmake-configure
        with:
          preset: linux_clang_debug
          build_type: Debug

      - name: "Build CMake"
        uses: ./.github/workflows/action-cmake-build
        with:
          preset: linux_clang_debug
          build_type: Debug

      - name: "Run clang-tidy"
        working-directory: ${{ env.build_dir }}
        run: ../scripts/check-clang-tidy.sh

      - name: "Verify"
        working-directory: ${{ env.build_dir }}
        run: ../scripts/verify-clang-tidy.sh

