on: push

jobs:
  Default:
    runs-on: ubuntu-latest
    container: bicompb/gcc:11-root
    env:
      build_dir: cmake-build-linux-unit-tests-default
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Run Unit Test default"
        uses: ./.github/workflows/action-unit-tests
        with:
          preset: linux_gcc_debug_unit_tests
          build_type: Debug

  Address_Sanitizer:
    runs-on: ubuntu-latest
    container: bicompb/gcc:11-root
    env:
      build_dir: cmake-build-linux-unit-tests-asan
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Run Unit Test with Address Sanitizer"
        uses: ./.github/workflows/action-unit-tests
        with:
          preset: linux_gcc_debug_unit_tests
          build_type: Debug
          sanitizer: "USE_ASAN"

  Leak_Sanitizer:
    runs-on: ubuntu-latest
    container: bicompb/gcc:11-root
    env:
      build_dir: cmake-build-linux-unit-tests-leak
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Run Unit Test with Leak Sanitizer"
        uses: ./.github/workflows/action-unit-tests
        with:
          preset: linux_gcc_debug_unit_tests
          build_type: Debug
          sanitizer: "USE_LEAK"

  UndefinedBehavior_Sanitizer:
    runs-on: ubuntu-latest
    container: bicompb/gcc:11-root
    env:
      build_dir: cmake-build-linux-unit-tests-undefined-behavior
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Run Unit Test with Leak Sanitizer"
        uses: ./.github/workflows/action-unit-tests
        with:
          preset: linux_gcc_debug_unit_tests
          build_type: Debug
          sanitizer: "USE_UBSAN"
